### ISSUE TITLE
Should we use this page?

### ISSUE THREAD

**Issue by bowTiesAreCool** [meow56/Kixley#1]
Should we use this, or [the old GitHub page](https://github.com/Kixley/Beta_Stages)?

**Comment by bowTiesAreCool** [comment]
I also definitely don't have the right privileges in this repo, it won't let me commit without making a pull request you have to approve.

**Comment by meow56** [comment]
Ah, sorry about the privilege thing. I... actually wasn't expecting you to find this, I've just been using this repo to test that the site works. Here, I'll give you privileges now.

**Comment by meow56** [comment]
Okay, done. Also apparently there exists bowtiesareverycool now?

**Comment by meow56** [comment]
Also, I'm gonna issue a few warnings about the code.
1) Don't leave functions hanging:
`function foo() {
  if(2 === 2) {
    bar();
  }
  alert("Don't do this!");
}`
waitForUserInput() uses setTimeout(), which hands control back to the server to avoid an infinite loop crash. Stuff after a function call will be run the next time you request an input. Instead, put your function in requestInput directly.
2) I've had to remove a lot of easter eggs cuz that's not how buttons work. Sorry ;-;
3) I tried to rewrite the story but the final encounter isn't very good. help plz
4) Custom errors are a thing now! I don't remember if this was in the Bitbucket, but make your custom error with 
`const err = new Error("Error message");
throw err;`
Any thanks for playing messages should read "Thanks for playing!" cuz that's the one I programmed in.

Anyways, I think that's all I want to tell you? I'm probably forgetting something though.

**Comment by bowTiesAreCool** [comment]
блин, still no proper access. Also, maybe you could give the access to the Kixley organization we made?

**Comment by bowTiesAreCool** [comment]
Checked my email, found a thing to respond to. Looks like I have proper access now.

**Comment by meow56** [comment]
cool
