### ISSUE TITLE
Music files in places/town/marketplace/inn

### ISSUE THREAD

**Issue by cbp2170** [meow56/Kixley#10]
Just played the game a bit, and I noticed a little problem. The player is usually not in `places()` for more than a second (if that), same with the town, inn, and marketplace. It seems that we don't really need separate music themes for each of these four locations as the player doesn't use them for very long, so there is just a very brief clip of the beginning of the music as the player whizzes through them. I think I will probably combine all four of these to use one music file, I just have to pick which one. What do you think?

**Comment by bowTiesAreCool** [comment]
My vote for which file to use
1. [Marketplace Theme](https://www.noteflight.com/scores/view/ddbb832dd9a927cbd9390534b3e5ff4bf8c736f8)
2. [Town Theme](https://www.noteflight.com/scores/view/98fffc04ddc31d8f513eca39ae77778ff290683b)
3. [(Alternate, currently unused) Places Theme](https://www.noteflight.com/scores/view/6c21ee7dc27a1da31ea00e45d9e6e52c01bd5b06)
4. [Places Theme](https://www.noteflight.com/scores/view/537ed85b4a2c0024861df2ac09bd218347ce1ee7)
5. [Inn Theme](https://www.noteflight.com/scores/view/85329cb88f69bc9beea761c6d99bd39b88914e9f)

**Comment by meow56** [comment]
I'd also prefer the shop theme.

However, I believe the shop theme is the only piece with percussion, which is...interesting. Especially because the fight music doesn't have drums.

**Comment by meow56** [comment]
Done, I suppose
