### ISSUE TITLE
Music?

### ISSUE THREAD

**Issue by meow56** [meow56/Kixley#9]
Hey, maybe we could finally use those music files!

**Comment by bowTiesAreCool** [comment]
Yeah, I'll try to get that going

**Comment by meow56** [comment]
cool

**Comment by bowTiesAreCool** [comment]
So the error in the music is that the variable I set to be the file is null. I assume this is a problem with my HTML, making my whole `document.getElementByID()` scheme not work. I seem to remember the music playing between boxes at one point though, so I think that old js is fine, but I don't remember what the HTML I used for it was.

**Comment by meow56** [comment]
Ok, let me see what I can do.

**Comment by meow56** [comment]
It works! Now just to make sure that it doesn't restart when we don't want it to...

**Comment by meow56** [comment]
Done!
